name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '4.2.0'
      - name: Build
        run: bazel build //waterfall/golang/server:server_bin_amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bazel-bin/waterfall/golang/server/linux_amd64_static_pure_stripped/server_bin_amd64
